const members=[
  {
    id:1,
    name:"hasya",
    email:'hasya@gmail.com',
    status:"active"
  },
  {
    id:2,
    name:"ram",
    email:'ram@gmail.com',
    status:"inactive"
  },
  {
    id:3,
    name:"prakash",
    email:'prkash@gmail.com',
    status:"active"
  },
 ]
 module.exports=members